#!/bin/bash
grdinfo $1 $2
gmtset D_FORMAT %.40f
info=(`grdinfo -C -M $1`)
REGION="${info[1]}/${info[2]}/${info[3]}/${info[4]}"
INTER="${info[7]}/${info[8]}"
echo $REGION
grd2xyz -S $2 | xyz2grd  -R$REGION -I$INTER -Gresampled-$2
#grdsample -R$REGION  $2   -Gresampled-$2 -I$INTER
grdmath $1 $1 resampled-$2 MUL NAN = $3

