#!/bin/bash
echo 'TexGen...
'
BASEPATH=/home/mkj/cvs/threadedStereo/
VRIP_HOME=$BASEPATH/vrip
MESHAGG=$PWD/mesh-agg/
export VRIP_DIR=$VRIP_HOME/src/vrip/
PATH=$PATH:$VRIP_HOME/bin
RUNDIR=$PWD
DICEDIR=$PWD/mesh-diced/
mkdir -p $DICEDIR
cd $DICEDIR
cd $RUNDIR
valgrind --gen-suppressions=all --leak-check=full --num-callers=40 --log-file=out --suppressions=opengl.supp --error-limit=no -v /home/mkj/cvs/threadedStereo/threadedStereo /media/atoll/PROCESSED_DATA/Tasmania200810/r20081014_052323_ohara_20_oneline/renav20081014/mesh20081016/ -n 3 --no_cached
