#!/bin/bash
echo 'TexGen...
'
BASEPATH=/home/mkj/cvs/threadedStereo/
VRIP_HOME=$BASEPATH/vrip
MESHAGG=$PWD/mesh-agg/
export VRIP_DIR=$VRIP_HOME/src/vrip/
PATH=$PATH:$VRIP_HOME/bin
RUNDIR=$PWD
DICEDIR=$PWD/mesh-diced/
mkdir -p $DICEDIR
cd $DICEDIR
cd $RUNDIR
valgrind --gen-suppressions=all --leak-check=full --num-callers=40 --log-file=out --suppressions=opengl.supp --error-limit=no -v /home/mkj/cvs/threadedStereo/genTex /media/reef/r20070524_042006_ng2_16_canyon_survey//stereo.cfg /media/reef/r20070524_042006_ng2_16_canyon_survey//recon.cfg -f /media/reef/r20070524_042006_ng2_16_canyon_survey//cache-tex/  -t 1 -n 3 #--lod-start 2
